### ISSUE TITLE
add : add a print automatically to available devices

### ISSUE THREAD

**Issue by teojunjie** [CS2113-AY1819S1-T09-1/main#42] opened 2018-10-12 15:07 UTC
As a student , i want to be able to add a print automatically to any available devices so that i can skip the hassle of waiting for a device to become available and be added to the general queue.

This issue is currently being addressed in pr #67. Please follow the pr to see the progress if needed.

**Comment by teojunjie** [comment] 2018-10-22 08:38
Currently, job is added to a binary tree sorted by a custom comparator, which in this case is the queue based on the priority determined by the custom comparator. However, machine will only get the next higher priority job if the machine is available which has to be completed by issue #40 done by @Ftywan .

**Comment by teojunjie** [comment] 2018-10-23 08:16
Changed the way job is added. Instead of adding it to a btree and using the observableset class, i have just maintained the observablelist class and a custom sorting comparator function to sort the list whenever a new job is added. The reason for doing so is because of the restrictions of the observableList class which doesnt allow a btree to be added to the list, if i insistently use a b tree , i must iterate through the list and add it the observable list which is time and space expensive. As compared to using FXCollections.sort function which optimizes the sorting algorithm and saves space since only one list is created.

**Comment by teojunjie** [comment] 2018-10-23 08:17
As of now, whenever a job is added , the ui is updated to display the most highest priority jobs

**Comment by Psyf** [comment] 2018-10-27 09:29
Actually I think the correct way is to assign me and de-assign yourself instead of closing.

**Comment by teojunjie** [comment] 2018-10-27 09:43
Ok sure i will do that now

**Comment by Psyf** [comment] 2018-10-30 02:46
Duplicate of #58 ; addressed in #78

**Closed by Psyf** 2018-10-30 02:46 UTC
Labels: priority.medium, type.enhancement, type.story
